# Generated by Django 5.2.6 on 2025-09-26 09:09

import src.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_recipe_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(null=True, upload_to=src.core.models.recipe_image_file_path),
        ),
    ]
